// lib/firebase_options.dart
// Generated by: flutterfire configure
// This file is updated with values from google-services.json

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOZ7CqaS5yl2iMwWUrDoXOvHu6WndeebQ',
    appId: '1:642473948656:android:828efe74da0d9a4d795935',
    messagingSenderId: '642473948656',
    projectId: 'clipcut-e2d7d',
    storageBucket: 'clipcut-e2d7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:642473948656:ios:YOUR_IOS_ID',
    messagingSenderId: '642473948656',
    projectId: 'clipcut-e2d7d',
    storageBucket: 'clipcut-e2d7d.firebasestorage.app',
    iosBundleId: 'com.clipcut.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:642473948656:web:YOUR_WEB_ID',
    messagingSenderId: '642473948656',
    projectId: 'clipcut-e2d7d',
    authDomain: 'clipcut-e2d7d.firebaseapp.com',
    storageBucket: 'clipcut-e2d7d.firebasestorage.app',
  );
}
